//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.08 at 12:49:13 AM CET 
//


package rs.ac.uns.ftn.a1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TAutorsko_delo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAutorsko_delo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo}TOsnovni_podaci_o_delu"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="podaci_o_preradi" type="{www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo}TOsnovni_podaci_o_delu" minOccurs="0"/&gt;
 *         &lt;element name="radni_odnos" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nacin_koriscenja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="vrsta" type="{www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo}vrsta_autorskog_dela" /&gt;
 *       &lt;attribute name="forma_zapisa" type="{www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo}forma_zapisa_autorskog_dela" /&gt;
 *       &lt;attribute name="prerada" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAutorsko_delo", propOrder = {
    "podaciOPreradi",
    "radniOdnos",
    "nacinKoriscenja"
})
public class TAutorskoDelo
    extends TOsnovniPodaciODelu
{

    @XmlElementRef(name = "podaci_o_preradi", namespace = "www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", type = JAXBElement.class, required = false)
    protected JAXBElement<TOsnovniPodaciODelu> podaciOPreradi;
    @XmlElement(name = "radni_odnos", required = true)
    protected String radniOdnos;
    @XmlElement(name = "nacin_koriscenja", required = true)
    protected String nacinKoriscenja;
    @XmlAttribute(name = "vrsta")
    protected VrstaAutorskogDela vrsta;
    @XmlAttribute(name = "forma_zapisa")
    protected FormaZapisaAutorskogDela formaZapisa;
    @XmlAttribute(name = "prerada")
    protected Boolean prerada;

    /**
     * Gets the value of the podaciOPreradi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TOsnovniPodaciODelu }{@code >}
     *     
     */
    public JAXBElement<TOsnovniPodaciODelu> getPodaciOPreradi() {
        return podaciOPreradi;
    }

    /**
     * Sets the value of the podaciOPreradi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TOsnovniPodaciODelu }{@code >}
     *     
     */
    public void setPodaciOPreradi(JAXBElement<TOsnovniPodaciODelu> value) {
        this.podaciOPreradi = value;
    }

    /**
     * Gets the value of the radniOdnos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRadniOdnos() {
        return radniOdnos;
    }

    /**
     * Sets the value of the radniOdnos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRadniOdnos(String value) {
        this.radniOdnos = value;
    }

    /**
     * Gets the value of the nacinKoriscenja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNacinKoriscenja() {
        return nacinKoriscenja;
    }

    /**
     * Sets the value of the nacinKoriscenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNacinKoriscenja(String value) {
        this.nacinKoriscenja = value;
    }

    /**
     * Gets the value of the vrsta property.
     * 
     * @return
     *     possible object is
     *     {@link VrstaAutorskogDela }
     *     
     */
    public VrstaAutorskogDela getVrsta() {
        return vrsta;
    }

    /**
     * Sets the value of the vrsta property.
     * 
     * @param value
     *     allowed object is
     *     {@link VrstaAutorskogDela }
     *     
     */
    public void setVrsta(VrstaAutorskogDela value) {
        this.vrsta = value;
    }

    /**
     * Gets the value of the formaZapisa property.
     * 
     * @return
     *     possible object is
     *     {@link FormaZapisaAutorskogDela }
     *     
     */
    public FormaZapisaAutorskogDela getFormaZapisa() {
        return formaZapisa;
    }

    /**
     * Sets the value of the formaZapisa property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormaZapisaAutorskogDela }
     *     
     */
    public void setFormaZapisa(FormaZapisaAutorskogDela value) {
        this.formaZapisa = value;
    }

    /**
     * Gets the value of the prerada property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrerada() {
        return prerada;
    }

    /**
     * Sets the value of the prerada property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrerada(Boolean value) {
        this.prerada = value;
    }

}
