//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.08 at 12:49:13 AM CET 
//


package rs.ac.uns.ftn.a1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vrsta_autorskog_dela.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="vrsta_autorskog_dela"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="knjizevno delo"/&gt;
 *     &lt;enumeration value="muzicko delo"/&gt;
 *     &lt;enumeration value="likovno delo"/&gt;
 *     &lt;enumeration value="racunarski program"/&gt;
 *     &lt;enumeration value="ostalo"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "vrsta_autorskog_dela")
@XmlEnum
public enum VrstaAutorskogDela {

    @XmlEnumValue("knjizevno delo")
    KNJIZEVNO_DELO("knjizevno delo"),
    @XmlEnumValue("muzicko delo")
    MUZICKO_DELO("muzicko delo"),
    @XmlEnumValue("likovno delo")
    LIKOVNO_DELO("likovno delo"),
    @XmlEnumValue("racunarski program")
    RACUNARSKI_PROGRAM("racunarski program"),
    @XmlEnumValue("ostalo")
    OSTALO("ostalo");
    private final String value;

    VrstaAutorskogDela(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VrstaAutorskogDela fromValue(String v) {
        for (VrstaAutorskogDela c: VrstaAutorskogDela.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
