//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 08:31:28 PM CET 
//


package rs.ac.uns.ftn.jaxb.a1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for forma_zapisa_autorskog_dela.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="forma_zapisa_autorskog_dela"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="stamparski tekst"/&gt;
 *     &lt;enumeration value="opticki disk"/&gt;
 *     &lt;enumeration value="ostalo"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "forma_zapisa_autorskog_dela")
@XmlEnum
public enum FormaZapisaAutorskogDela {

    @XmlEnumValue("stamparski tekst")
    STAMPARSKI_TEKST("stamparski tekst"),
    @XmlEnumValue("opticki disk")
    OPTICKI_DISK("opticki disk"),
    @XmlEnumValue("ostalo")
    OSTALO("ostalo");
    private final String value;

    FormaZapisaAutorskogDela(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FormaZapisaAutorskogDela fromValue(String v) {
        for (FormaZapisaAutorskogDela c: FormaZapisaAutorskogDela.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String toString() {
        return value;
    }
}
