//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.08 at 06:40:54 PM CET 
//


package rs.ac.uns.ftn.jaxb.a1;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.zahtevzaautorskodelo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Adresa_QNAME = new QName("www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", "Adresa");
    private final static QName _ZahtevZaAutorskoDeloPrilozi_QNAME = new QName("www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", "Prilozi");
    private final static QName _TOsnovniPodaciODeluIdentifikatorAlternativniNaslov_QNAME = new QName("www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", "Alternativni_naslov");
    private final static QName _TPodnosilacPunomocnik_QNAME = new QName("www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", "Punomocnik");
    private final static QName _TPodnosilacPravnoLice_QNAME = new QName("www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", "Pravno_lice");
    private final static QName _TAutorPseudonim_QNAME = new QName("www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", "Pseudonim");
    private final static QName _TAutorGodinaSmrti_QNAME = new QName("www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", "Godina_smrti");
    private final static QName _TAutorskoDeloPodaciOOriginalu_QNAME = new QName("www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", "Podaci_o_originalu");
    private final static QName _TAutorskoDeloRadniOdnos_QNAME = new QName("www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", "Radni_odnos");
    private final static QName _TAutorskoDeloNacinKoriscenja_QNAME = new QName("www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", "Nacin_koriscenja");
    private final static QName _ZahtevZaAutorskoDeloPodnosilacTelefon_QNAME = new QName("www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", "Telefon");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.zahtevzaautorskodelo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZahtevZaAutorskoDelo }
     * 
     */
    public ZahtevZaAutorskoDelo createZahtevZaAutorskoDelo() {
        return new ZahtevZaAutorskoDelo();
    }

    /**
     * Create an instance of {@link TOsnovniPodaciODelu }
     * 
     */
    public TOsnovniPodaciODelu createTOsnovniPodaciODelu() {
        return new TOsnovniPodaciODelu();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link ZahtevZaAutorskoDelo.Podnosilac }
     * 
     */
    public ZahtevZaAutorskoDelo.Podnosilac createZahtevZaAutorskoDeloPodnosilac() {
        return new ZahtevZaAutorskoDelo.Podnosilac();
    }

    /**
     * Create an instance of {@link TAutorskoDelo }
     * 
     */
    public TAutorskoDelo createTAutorskoDelo() {
        return new TAutorskoDelo();
    }

    /**
     * Create an instance of {@link TPrilog }
     * 
     */
    public TPrilog createTPrilog() {
        return new TPrilog();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link TAutor }
     * 
     */
    public TAutor createTAutor() {
        return new TAutor();
    }

    /**
     * Create an instance of {@link TAutori }
     * 
     */
    public TAutori createTAutori() {
        return new TAutori();
    }

    /**
     * Create an instance of {@link TPodnosilac }
     * 
     */
    public TPodnosilac createTPodnosilac() {
        return new TPodnosilac();
    }

    /**
     * Create an instance of {@link TOsnovniPodaciODelu.Identifikator }
     * 
     */
    public TOsnovniPodaciODelu.Identifikator createTOsnovniPodaciODeluIdentifikator() {
        return new TOsnovniPodaciODelu.Identifikator();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Adresa }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Adresa }{@code >}
     */
    @XmlElementDecl(namespace = "www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", name = "Adresa")
    public JAXBElement<Adresa> createAdresa(Adresa value) {
        return new JAXBElement<Adresa>(_Adresa_QNAME, Adresa.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPrilog }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TPrilog }{@code >}
     */
    @XmlElementDecl(namespace = "www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", name = "Prilozi", scope = ZahtevZaAutorskoDelo.class)
    public JAXBElement<TPrilog> createZahtevZaAutorskoDeloPrilozi(TPrilog value) {
        return new JAXBElement<TPrilog>(_ZahtevZaAutorskoDeloPrilozi_QNAME, TPrilog.class, ZahtevZaAutorskoDelo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", name = "Alternativni_naslov", scope = TOsnovniPodaciODelu.Identifikator.class)
    public JAXBElement<String> createTOsnovniPodaciODeluIdentifikatorAlternativniNaslov(String value) {
        return new JAXBElement<String>(_TOsnovniPodaciODeluIdentifikatorAlternativniNaslov_QNAME, String.class, TOsnovniPodaciODelu.Identifikator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFizickoLice }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TFizickoLice }{@code >}
     */
    @XmlElementDecl(namespace = "www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", name = "Punomocnik", scope = TPodnosilac.class)
    public JAXBElement<TFizickoLice> createTPodnosilacPunomocnik(TFizickoLice value) {
        return new JAXBElement<TFizickoLice>(_TPodnosilacPunomocnik_QNAME, TFizickoLice.class, TPodnosilac.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPravnoLice }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TPravnoLice }{@code >}
     */
    @XmlElementDecl(namespace = "www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", name = "Pravno_lice", scope = TPodnosilac.class)
    public JAXBElement<TPravnoLice> createTPodnosilacPravnoLice(TPravnoLice value) {
        return new JAXBElement<TPravnoLice>(_TPodnosilacPravnoLice_QNAME, TPravnoLice.class, TPodnosilac.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", name = "Pseudonim", scope = TAutor.class)
    public JAXBElement<String> createTAutorPseudonim(String value) {
        return new JAXBElement<String>(_TAutorPseudonim_QNAME, String.class, TAutor.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", name = "Godina_smrti", scope = TAutor.class)
    public JAXBElement<BigInteger> createTAutorGodinaSmrti(BigInteger value) {
        return new JAXBElement<BigInteger>(_TAutorGodinaSmrti_QNAME, BigInteger.class, TAutor.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOsnovniPodaciODelu }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TOsnovniPodaciODelu }{@code >}
     */
    @XmlElementDecl(namespace = "www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", name = "Podaci_o_originalu", scope = TAutorskoDelo.class)
    public JAXBElement<TOsnovniPodaciODelu> createTAutorskoDeloPodaciOOriginalu(TOsnovniPodaciODelu value) {
        return new JAXBElement<TOsnovniPodaciODelu>(_TAutorskoDeloPodaciOOriginalu_QNAME, TOsnovniPodaciODelu.class, TAutorskoDelo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", name = "Radni_odnos", scope = TAutorskoDelo.class)
    public JAXBElement<String> createTAutorskoDeloRadniOdnos(String value) {
        return new JAXBElement<String>(_TAutorskoDeloRadniOdnos_QNAME, String.class, TAutorskoDelo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", name = "Nacin_koriscenja", scope = TAutorskoDelo.class)
    public JAXBElement<String> createTAutorskoDeloNacinKoriscenja(String value) {
        return new JAXBElement<String>(_TAutorskoDeloNacinKoriscenja_QNAME, String.class, TAutorskoDelo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", name = "Telefon", scope = ZahtevZaAutorskoDelo.Podnosilac.class)
    public JAXBElement<String> createZahtevZaAutorskoDeloPodnosilacTelefon(String value) {
        return new JAXBElement<String>(_ZahtevZaAutorskoDeloPodnosilacTelefon_QNAME, String.class, ZahtevZaAutorskoDelo.Podnosilac.class, value);
    }

}
