//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 08:31:28 PM CET 
//


package rs.ac.uns.ftn.jaxb.a1;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import rs.ac.uns.ftn.jaxb.zajednicko.TFizickoLice;


/**
 * <p>Java class for TAutor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAutor"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.ftn.uns.ac.rs/zaj}TFizicko_lice"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Pseudonim" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Godina_smrti" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="primarni" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="anonimni" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAutor", propOrder = {
    "pseudonim",
    "godinaSmrti"
})
public class TAutor
    extends TFizickoLice
{

    @XmlElement(name = "Pseudonim")
    protected String pseudonim;
    @XmlElement(name = "Godina_smrti")
    protected BigInteger godinaSmrti;
    @XmlAttribute(name = "primarni")
    protected Boolean primarni;
    @XmlAttribute(name = "anonimni")
    protected Boolean anonimni;

    /**
     * Gets the value of the pseudonim property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPseudonim() {
        return pseudonim;
    }

    /**
     * Sets the value of the pseudonim property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPseudonim(String value) {
        this.pseudonim = value;
    }

    /**
     * Gets the value of the godinaSmrti property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGodinaSmrti() {
        return godinaSmrti;
    }

    /**
     * Sets the value of the godinaSmrti property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGodinaSmrti(BigInteger value) {
        this.godinaSmrti = value;
    }

    /**
     * Gets the value of the primarni property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrimarni() {
        return primarni;
    }

    /**
     * Sets the value of the primarni property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrimarni(Boolean value) {
        this.primarni = value;
    }

    /**
     * Gets the value of the anonimni property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAnonimni() {
        return anonimni;
    }

    /**
     * Sets the value of the anonimni property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAnonimni(Boolean value) {
        this.anonimni = value;
    }

    @Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();
        buffer.append(super.toString());
        
		if(pseudonim != null) {
			buffer.append("\n\t\t - Pseudonim: ");
	        buffer.append(pseudonim);
		}
        
		if(godinaSmrti != null) {
			buffer.append("\n\t\t - Godina smrti: ");
	        buffer.append(godinaSmrti);
		}
        
        if(primarni!=null) {
        	String isPrimarni = primarni ? "DA" : "NE";

            buffer.append("\n\t\t - Primarni: ");
            buffer.append(isPrimarni);
        }
        
        if(anonimni != null) {
            String isAnonimni = anonimni ? "DA" : "NE";

            buffer.append("\n\t\t - Anonimni: ");
            buffer.append(isAnonimni);
        }

        return buffer.toString();
	}


    
}
