//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.08 at 06:40:54 PM CET 
//


package rs.ac.uns.ftn.jaxb.a1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TPodnosilac complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TPodnosilac"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Autor" type="{www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo}TAutor" minOccurs="0"/&gt;
 *         &lt;element name="Punomocnik" type="{www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo}TFizicko_lice" minOccurs="0"/&gt;
 *         &lt;element name="Pravno_lice" type="{www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo}TPravno_lice" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPodnosilac", propOrder = {
    "autor",
    "punomocnik",
    "pravnoLice"
})
public class TPodnosilac {

    @XmlElement(name = "Autor")
    protected TAutor autor;
    @XmlElementRef(name = "Punomocnik", namespace = "www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", type = JAXBElement.class, required = false)
    protected JAXBElement<TFizickoLice> punomocnik;
    @XmlElementRef(name = "Pravno_lice", namespace = "www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", type = JAXBElement.class, required = false)
    protected JAXBElement<TPravnoLice> pravnoLice;

    /**
     * Gets the value of the autor property.
     * 
     * @return
     *     possible object is
     *     {@link TAutor }
     *     
     */
    public TAutor getAutor() {
        return autor;
    }

    /**
     * Sets the value of the autor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAutor }
     *     
     */
    public void setAutor(TAutor value) {
        this.autor = value;
    }

    /**
     * Gets the value of the punomocnik property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TFizickoLice }{@code >}
     *     
     */
    public JAXBElement<TFizickoLice> getPunomocnik() {
        return punomocnik;
    }

    /**
     * Sets the value of the punomocnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TFizickoLice }{@code >}
     *     
     */
    public void setPunomocnik(JAXBElement<TFizickoLice> value) {
        this.punomocnik = value;
    }

    /**
     * Gets the value of the pravnoLice property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TPravnoLice }{@code >}
     *     
     */
    public JAXBElement<TPravnoLice> getPravnoLice() {
        return pravnoLice;
    }

    /**
     * Sets the value of the pravnoLice property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TPravnoLice }{@code >}
     *     
     */
    public void setPravnoLice(JAXBElement<TPravnoLice> value) {
        this.pravnoLice = value;
    }

}
