//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.08 at 06:40:54 PM CET 
//


package rs.ac.uns.ftn.jaxb.a1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="Zavod" type="{www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo}TPravno_lice"/&gt;
 *         &lt;element name="Podnosilac"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;all&gt;
 *                   &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Telefon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Podaci_o_podnosiocu" type="{www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo}TPodnosilac"/&gt;
 *                 &lt;/all&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Autorsko_delo" type="{www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo}TAutorsko_delo"/&gt;
 *         &lt;element name="Prilozi" type="{www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo}TPrilog" minOccurs="0" form="qualified"/&gt;
 *       &lt;/all&gt;
 *       &lt;attribute name="naslov" type="{http://www.w3.org/2001/XMLSchema}string" fixed="\u0417\u0410\u0425\u0422\u0415\u0412 \u0417\u0410 \u0423\u041d\u041e\u0428\u0415\u040a\u0415 \u0423 \u0415\u0412\u0418\u0414\u0415\u041d\u0426\u0418\u0408\u0423 \u0418 \u0414\u0415\u041f\u041e\u041d\u041e\u0412\u0410\u040a\u0415 \u0410\u0423\u0422\u041e\u0420\u0421\u041a\u0418\u0425 \u0414\u0415\u041b\u0410" /&gt;
 *       &lt;attribute name="broj_prijave" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Zahtev_za_autorsko_delo")
public class ZahtevZaAutorskoDelo {

    @XmlElement(name = "Zavod", required = true)
    protected TPravnoLice zavod;
    @XmlElement(name = "Podnosilac", required = true)
    protected ZahtevZaAutorskoDelo.Podnosilac podnosilac;
    @XmlElement(name = "Autorsko_delo", required = true)
    protected TAutorskoDelo autorskoDelo;
    @XmlElementRef(name = "Prilozi", namespace = "www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", type = JAXBElement.class, required = false)
    protected JAXBElement<TPrilog> prilozi;
    @XmlAttribute(name = "naslov")
    protected String naslov;
    @XmlAttribute(name = "broj_prijave")
    protected String brojPrijave;
    @XmlAttribute(name = "datum_podnosenja")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPodnosenja;

    /**
     * Gets the value of the zavod property.
     * 
     * @return
     *     possible object is
     *     {@link TPravnoLice }
     *     
     */
    public TPravnoLice getZavod() {
        return zavod;
    }

    /**
     * Sets the value of the zavod property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPravnoLice }
     *     
     */
    public void setZavod(TPravnoLice value) {
        this.zavod = value;
    }

    /**
     * Gets the value of the podnosilac property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaAutorskoDelo.Podnosilac }
     *     
     */
    public ZahtevZaAutorskoDelo.Podnosilac getPodnosilac() {
        return podnosilac;
    }

    /**
     * Sets the value of the podnosilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaAutorskoDelo.Podnosilac }
     *     
     */
    public void setPodnosilac(ZahtevZaAutorskoDelo.Podnosilac value) {
        this.podnosilac = value;
    }

    /**
     * Gets the value of the autorskoDelo property.
     * 
     * @return
     *     possible object is
     *     {@link TAutorskoDelo }
     *     
     */
    public TAutorskoDelo getAutorskoDelo() {
        return autorskoDelo;
    }

    /**
     * Sets the value of the autorskoDelo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAutorskoDelo }
     *     
     */
    public void setAutorskoDelo(TAutorskoDelo value) {
        this.autorskoDelo = value;
    }

    /**
     * Gets the value of the prilozi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TPrilog }{@code >}
     *     
     */
    public JAXBElement<TPrilog> getPrilozi() {
        return prilozi;
    }

    /**
     * Sets the value of the prilozi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TPrilog }{@code >}
     *     
     */
    public void setPrilozi(JAXBElement<TPrilog> value) {
        this.prilozi = value;
    }

    /**
     * Gets the value of the naslov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaslov() {
        if (naslov == null) {
            return "\u0417\u0410\u0425\u0422\u0415\u0412 \u0417\u0410 \u0423\u041d\u041e\u0428\u0415\u040a\u0415 \u0423 \u0415\u0412\u0418\u0414\u0415\u041d\u0426\u0418\u0408\u0423 \u0418 \u0414\u0415\u041f\u041e\u041d\u041e\u0412\u0410\u040a\u0415 \u0410\u0423\u0422\u041e\u0420\u0421\u041a\u0418\u0425 \u0414\u0415\u041b\u0410";
        } else {
            return naslov;
        }
    }

    /**
     * Sets the value of the naslov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaslov(String value) {
        this.naslov = value;
    }

    /**
     * Gets the value of the brojPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojPrijave() {
        return brojPrijave;
    }

    /**
     * Sets the value of the brojPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojPrijave(String value) {
        this.brojPrijave = value;
    }

    /**
     * Gets the value of the datumPodnosenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPodnosenja() {
        return datumPodnosenja;
    }

    /**
     * Sets the value of the datumPodnosenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPodnosenja(XMLGregorianCalendar value) {
        this.datumPodnosenja = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;all&gt;
     *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Telefon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Podaci_o_podnosiocu" type="{www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo}TPodnosilac"/&gt;
     *       &lt;/all&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Podnosilac {

        @XmlElement(name = "Email")
        protected String email;
        @XmlElementRef(name = "Telefon", namespace = "www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo", type = JAXBElement.class, required = false)
        protected JAXBElement<String> telefon;
        @XmlElement(name = "Podaci_o_podnosiocu", required = true)
        protected TPodnosilac podaciOPodnosiocu;

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmail(String value) {
            this.email = value;
        }

        /**
         * Gets the value of the telefon property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public JAXBElement<String> getTelefon() {
            return telefon;
        }

        /**
         * Sets the value of the telefon property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setTelefon(JAXBElement<String> value) {
            this.telefon = value;
        }

        /**
         * Gets the value of the podaciOPodnosiocu property.
         * 
         * @return
         *     possible object is
         *     {@link TPodnosilac }
         *     
         */
        public TPodnosilac getPodaciOPodnosiocu() {
            return podaciOPodnosiocu;
        }

        /**
         * Sets the value of the podaciOPodnosiocu property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPodnosilac }
         *     
         */
        public void setPodaciOPodnosiocu(TPodnosilac value) {
            this.podaciOPodnosiocu = value;
        }

    }


	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();
        buffer.append("- Zahtev za autorsko delo: ");
        
        buffer.append("\n\t - Naslov: ");
        buffer.append(naslov);

        buffer.append("\n\t - Broj prijave: ");
        buffer.append(brojPrijave);

        buffer.append("\n\t - Datum podnosenja: ");
        buffer.append(datumPodnosenja);

        buffer.append("\n\t - Zavod: ");
        buffer.append(zavod);

        buffer.append("\n\t - podnosilac: ");
        buffer.append(podnosilac);

        buffer.append("\n\t - Autorsko delo: ");
        buffer.append(autorskoDelo);

        buffer.append("\n\t - Prilozi: ");
        buffer.append(prilozi.toString());

        return buffer.toString();
	}
}
