<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:h="http://www.w3.org/1999/xhtml"
    xmlns:pred="http://examples/predicate/">
  <rdf:Description rdf:about="%1$s">
    <pred:datum_podnosenja rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">%2$s</pred:datum_podnosenja>
    <pred:autorsko_delo>%3$s</pred:autorsko_delo>
    <pred:primarni_autor>%4$s</pred:primarni_autor>
    <pred:koautor>%5$s</pred:koautor>
    <pred:podnosilac rdf:resource="%6$s"/>
    <pred:ime_prodnosioca>%7$s</pred:ime_prodnosioca>
    
  </rdf:Description>
</rdf:RDF>