//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 08:31:28 PM CET 
//


package rs.ac.uns.ftn.jaxb.a1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;



/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.a1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _IdAutorksogDeka_QNAME = new QName("http://ftn.uns.ac.rs/a1", "idAutorskogDela");
    private final static QName _TOsnovniPodaciODeluIdentifikatorAlternativniNaslov_QNAME = new QName("http://ftn.uns.ac.rs/a1", "Alternativni_naslov");
    private final static QName _TAutorskoDeloPodaciOOriginalu_QNAME = new QName("http://ftn.uns.ac.rs/a1", "Podaci_o_originalu");
    private final static QName _TAutorskoDeloRadniOdnos_QNAME = new QName("http://ftn.uns.ac.rs/a1", "Radni_odnos");
    private final static QName _TAutorskoDeloNacinKoriscenja_QNAME = new QName("http://ftn.uns.ac.rs/a1", "Nacin_koriscenja");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.a1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TOsnovniPodaciODelu }
     * 
     */
    public TOsnovniPodaciODelu createTOsnovniPodaciODelu() {
        return new TOsnovniPodaciODelu();
    }

    /**
     * Create an instance of {@link ZahtevZaAutorskoDelo }
     * 
     */
    public ZahtevZaAutorskoDelo createZahtevZaAutorskoDelo() {
        return new ZahtevZaAutorskoDelo();
    }

    /**
     * Create an instance of {@link TZavod }
     * 
     */
    public TZavod createTZavod() {
        return new TZavod();
    }

    /**
     * Create an instance of {@link TPodnosilac }
     * 
     */
    public TPodnosilac createTPodnosilac() {
        return new TPodnosilac();
    }

    /**
     * Create an instance of {@link TAutorskoDelo }
     * 
     */
    public TAutorskoDelo createTAutorskoDelo() {
        return new TAutorskoDelo();
    }

    /**
     * Create an instance of {@link TPrilozi }
     * 
     */
    public TPrilozi createTPrilozi() {
        return new TPrilozi();
    }
    /**
     * Create an instance of {@link TPrilog }
     * 
     */
    public TPrilog createTPrilog() {
        return new TPrilog();
    }
    /**
     * Create an instance of {@link TAutor }
     * 
     */
    public TAutor createTAutor() {
        return new TAutor();
    }

    /**
     * Create an instance of {@link TAutori }
     * 
     */
    public TAutori createTAutori() {
        return new TAutori();
    }

    /**
     * Create an instance of {@link TOsnovniPodaciODelu.Identifikator }
     * 
     */
    public TOsnovniPodaciODelu.Identifikator createTOsnovniPodaciODeluIdentifikator() {
        return new TOsnovniPodaciODelu.Identifikator();
    }
    
    /**
     * Create an instance of {@link TAutori }
     * 
     */
    public IdAutorskogDela createIdAutorskogDela() {
        return new IdAutorskogDela();
    } 

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/a1", name = "Alternativni_naslov", scope = TOsnovniPodaciODelu.Identifikator.class)
    public JAXBElement<String> createTOsnovniPodaciODeluIdentifikatorAlternativniNaslov(String value) {
        return new JAXBElement<String>(_TOsnovniPodaciODeluIdentifikatorAlternativniNaslov_QNAME, String.class, TOsnovniPodaciODelu.Identifikator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOsnovniPodaciODelu }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TOsnovniPodaciODelu }{@code >}
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/a1", name = "Podaci_o_originalu", scope = TAutorskoDelo.class)
    public JAXBElement<TOsnovniPodaciODelu> createTAutorskoDeloPodaciOOriginalu(TOsnovniPodaciODelu value) {
        return new JAXBElement<TOsnovniPodaciODelu>(_TAutorskoDeloPodaciOOriginalu_QNAME, TOsnovniPodaciODelu.class, TAutorskoDelo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/a1", name = "Radni_odnos", scope = TAutorskoDelo.class)
    public JAXBElement<String> createTAutorskoDeloRadniOdnos(String value) {
        return new JAXBElement<String>(_TAutorskoDeloRadniOdnos_QNAME, String.class, TAutorskoDelo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/a1", name = "Nacin_koriscenja", scope = TAutorskoDelo.class)
    public JAXBElement<String> createTAutorskoDeloNacinKoriscenja(String value) {
        return new JAXBElement<String>(_TAutorskoDeloNacinKoriscenja_QNAME, String.class, TAutorskoDelo.class, value);
    }
    
//    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/a1", name = "idAutorskogDela", scope = IdAutorskogDela.class)
//    public JAXBElement<String> createIdAutorskogDela(String value) {
//        return new JAXBElement<String>(_IdAutorksogDeka_QNAME, String.class, IdAutorskogDela.class, value);
//    }

}
