//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 08:31:28 PM CET 
//


package rs.ac.uns.ftn.jaxb.a1;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for TOsnovni_podaci_o_delu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TOsnovni_podaci_o_delu"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Identifikator"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;all&gt;
 *                   &lt;element name="Naslov" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Alternativni_naslov" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/all&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Autori" type="{http://ftn.uns.ac.rs/a1}TAutori" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TOsnovni_podaci_o_delu", propOrder = {
    "identifikator",
    "autori"
})
@XmlSeeAlso({
    TAutorskoDelo.class
})
public class TOsnovniPodaciODelu {

    @XmlElement(name = "Identifikator", required = true)
    protected TOsnovniPodaciODelu.Identifikator identifikator;
    @XmlElement(name = "Autori")
    protected TAutori autori;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();
    /**
     * Gets the value of the identifikator property.
     * 
     * @return
     *     possible object is
     *     {@link TOsnovniPodaciODelu.Identifikator }
     *     
     */
    public TOsnovniPodaciODelu.Identifikator getIdentifikator() {
        return identifikator;
    }

    /**
     * Sets the value of the identifikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOsnovniPodaciODelu.Identifikator }
     *     
     */
    public void setIdentifikator(TOsnovniPodaciODelu.Identifikator value) {
        this.identifikator = value;
    }

    /**
     * Gets the value of the autori property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the autori property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAutori().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TAutori }
     * 
     * 
     */
    public TAutori getAutori() {
        return autori;
    }
    
    public void setAutori(TAutori autori) {
        this.autori = autori;
    }

    

    public Map<QName, String> getOtherAttributes() {
		return otherAttributes;
	}



	/**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;all&gt;
     *         &lt;element name="Naslov" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Alternativni_naslov" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/all&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Identifikator {

        @XmlElement(name = "Naslov", required = true)
        protected String naslov;
        @XmlElement(name = "Alternativni_naslov", namespace = "http://ftn.uns.ac.rs/a1", required = false)
        protected String alternativniNaslov;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();
        /**
         * Gets the value of the naslov property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaslov() {
            return naslov;
        }

        /**
         * Sets the value of the naslov property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaslov(String value) {
            this.naslov = value;
        }

        /**
         * Gets the value of the alternativniNaslov property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getAlternativniNaslov() {
            return alternativniNaslov;
        }

        /**
         * Sets the value of the alternativniNaslov property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setAlternativniNaslov(String value) {
            this.alternativniNaslov = value;
        }
        

		public Map<QName, String> getOtherAttributes() {
			return otherAttributes;
		}

		@Override
		public String toString() {
			StringBuffer buffer = new StringBuffer();
	        buffer.append("\n\t\t\t - Naslov: ");
	        buffer.append(naslov);
	        
	        if(alternativniNaslov != null) {
	        	buffer.append("\n\t\t\t - Alternativni naslov: ");
		        buffer.append(alternativniNaslov);
	        }

	        return buffer.toString();
			
		}
    }


	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();
        buffer.append("\n\t\t Identifikator: ");
        buffer.append(identifikator);

        if(autori!=null) {
        	buffer.append("\n\t\t Autori: ");
          	buffer.append(autori.toString());	
        }
        

        return buffer.toString();
	}
    
    

}
