//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 08:31:28 PM CET 
//


package rs.ac.uns.ftn.jaxb.a1;

import java.util.HashMap;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for TPrilog complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TPrilog"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="Prisutan_opis" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Prisutan_primer" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPrilozi", propOrder = {

})
public class TPrilozi {

    @XmlElement(name = "Prisutan_opis", nillable=true, required = false)
    protected TPrilog prisutanOpis;
    @XmlElement(name = "Prisutan_primer", nillable=true, required = false)
    protected TPrilog prisutanPrimer;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the prisutanOpis property.
     * 
     */
    public TPrilog getPrisutanOpis() {
        return prisutanOpis;
    }

    /**
     * Sets the value of the prisutanOpis property.
     * 
     */
    public void setPrisutanOpis(TPrilog value) {
        this.prisutanOpis = value;
    }

    /**
     * Gets the value of the prisutanPrimer property.
     * 
     */
    public TPrilog getPrisutanPrimer() {
        return prisutanPrimer;
    }

    /**
     * Sets the value of the prisutanPrimer property.
     * 
     */
    public void setPrisutanPrimer(TPrilog value) {
        this.prisutanPrimer = value;
    }

    public Map<QName, String> getOtherAttributes() {
		return otherAttributes;
	}

	@Override
    public String toString() {
		String opis = (prisutanOpis != null && !prisutanOpis.equals(""))? "DA" : "NE";
		String primer = (prisutanPrimer != null && !prisutanPrimer.equals("")) ? "DA" : "NE";
		
		StringBuffer buffer = new StringBuffer();
		buffer.append("\n\t\t");
		buffer.append("Prisutan opis: ");
		buffer.append(opis);
		buffer.append("\n\t\t");
		buffer.append("Prisutan primer: ");
		buffer.append(primer);
		return buffer.toString();
    }
}
