//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 08:31:28 PM CET 
//


package rs.ac.uns.ftn.jaxb.a1;

import java.util.Base64;
import java.util.HashMap;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for TPrilog complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TPrilog"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="Prisutan_opis" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Prisutan_primer" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPrilog", namespace = "http://ftn.uns.ac.rs/a1", propOrder = {
        "putanjaDoFajla",
        "dostavljeno"
})
public class TPrilog {

    @XmlElement(name = "Putanja_do_fajla", namespace = "http://ftn.uns.ac.rs/a1")
    protected String putanjaDoFajla;
    @XmlElement(name = "Dostavljeno", namespace = "http://ftn.uns.ac.rs/a1")
    protected Boolean dostavljeno;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();
    /**
     * Gets the value of the putanjaDoFajla property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPutanjaDoFajla() {
        return putanjaDoFajla;
    }

    /**
     * Sets the value of the putanjaDoFajla property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPutanjaDoFajla(String value) {
        this.putanjaDoFajla = value;
    }

    /**
     * Gets the value of the dostavljeno property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isDostavljeno() {
        return dostavljeno;
    }

    /**
     * Sets the value of the dostavljeno property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setDostavljeno(Boolean value) {
        this.dostavljeno = value;
    }

    public Map<QName, String> getOtherAttributes() {
		return otherAttributes;
	}

	public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append("\n\t\t\t - Putanja do fajla: ");
        buffer.append(putanjaDoFajla);
        buffer.append("\n\t\t\t - Da li je dostavljeno: ");
        if (dostavljeno) {
            buffer.append("da");
        } else {
            buffer.append("ne");
        }

        return buffer.toString();
    }
}
