//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 08:31:28 PM CET 
//


package rs.ac.uns.ftn.jaxb.a1;

import java.util.HashMap;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="Zavod" type="{http://ftn.uns.ac.rs/a1}TZavod"/&gt;
 *         &lt;element name="Podnosilac" type="{http://ftn.uns.ac.rs/a1}TPodnosilac"/&gt;
 *         &lt;element name="Autorsko_delo" type="{http://ftn.uns.ac.rs/a1}TAutorsko_delo"/&gt;
 *         &lt;element name="Prilozi" type="{http://ftn.uns.ac.rs/a1}TPrilog" minOccurs="0" form="qualified"/&gt;
 *       &lt;/all&gt;
 *       &lt;attribute name="naslov" type="{http://www.w3.org/2001/XMLSchema}string" fixed="\u0417\u0410\u0425\u0422\u0415\u0412 \u0417\u0410 \u0423\u041d\u041e\u0428\u0415\u040a\u0415 \u0423 \u0415\u0412\u0418\u0414\u0415\u041d\u0426\u0418\u0408\u0423 \u0418 \u0414\u0415\u041f\u041e\u041d\u041e\u0412\u0410\u040a\u0415 \u0410\u0423\u0422\u041e\u0420\u0421\u041a\u0418\u0425 \u0414\u0415\u041b\u0410" /&gt;
 *       &lt;attribute name="broj_prijave" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"idAutorskogDela","zavod", "podnosilac", "autorskoDelo", "prilozi"
})
@XmlRootElement(name = "Zahtev_za_autorsko_delo")
public class ZahtevZaAutorskoDelo {

	@XmlElement()
	protected IdAutorskogDela idAutorskogDela;
	@XmlElement(name = "Zavod", required = true)
    protected TZavod zavod;
    @XmlElement(name = "Podnosilac", required = true)
    protected TPodnosilac podnosilac;
    @XmlElement(name = "Autorsko_delo", required = true)
    protected TAutorskoDelo autorskoDelo;
    @XmlElement(name = "Prilozi")
    protected TPrilog prilozi;
    @XmlAttribute(name = "naslov")
    protected String naslov;
    @XmlAttribute(name = "broj_prijave")
    protected String brojPrijave;
    @XmlAttribute(name = "datum_podnosenja")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPodnosenja;
    @XmlAttribute(name = "status")
    protected StatusZahteva status;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    
    public IdAutorskogDela getIdAutorskogDela() {
		return idAutorskogDela;
	}

	public void setIdAutorskogDela(IdAutorskogDela idAutorskogDela) {
		this.idAutorskogDela = idAutorskogDela;
	}
    /**
     * Gets the value of the zavod property.
     * 
     * @return
     *     possible object is
     *     {@link TZavod }
     *     
     */
    public TZavod getZavod() {
        return zavod;
    }

    /**
     * Sets the value of the zavod property.
     * 
     * @param value
     *     allowed object is
     *     {@link TZavod }
     *     
     */
    public void setZavod(TZavod value) {
        this.zavod = value;
    }

    /**
     * Gets the value of the podnosilac property.
     * 
     * @return
     *     possible object is
     *     {@link TPodnosilac }
     *     
     */
    public TPodnosilac getPodnosilac() {
        return podnosilac;
    }

    /**
     * Sets the value of the podnosilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPodnosilac }
     *     
     */
    public void setPodnosilac(TPodnosilac value) {
        this.podnosilac = value;
    }

    /**
     * Gets the value of the autorskoDelo property.
     * 
     * @return
     *     possible object is
     *     {@link TAutorskoDelo }
     *     
     */
    public TAutorskoDelo getAutorskoDelo() {
        return autorskoDelo;
    }

    /**
     * Sets the value of the autorskoDelo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAutorskoDelo }
     *     
     */
    public void setAutorskoDelo(TAutorskoDelo value) {
        this.autorskoDelo = value;
    }

    /**
     * Gets the value of the prilozi property.
     * 
     * @return
     *     possible object is
     *     {@link TPrilog }
     *     
     */
    public TPrilog getPrilozi() {
        return prilozi;
    }

    /**
     * Sets the value of the prilozi property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPrilog }
     *     
     */
    public void setPrilozi(TPrilog value) {
        this.prilozi = value;
    }

    /**
     * Gets the value of the naslov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaslov() {
        if (naslov == null) {
            return "\u0417\u0410\u0425\u0422\u0415\u0412 \u0417\u0410 \u0423\u041d\u041e\u0428\u0415\u040a\u0415 \u0423 \u0415\u0412\u0418\u0414\u0415\u041d\u0426\u0418\u0408\u0423 \u0418 \u0414\u0415\u041f\u041e\u041d\u041e\u0412\u0410\u040a\u0415 \u0410\u0423\u0422\u041e\u0420\u0421\u041a\u0418\u0425 \u0414\u0415\u041b\u0410";
        } else {
            return naslov;
        }
    }

    /**
     * Sets the value of the naslov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaslov(String value) {
        this.naslov = value;
    }

    /**
     * Gets the value of the brojPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojPrijave() {
        return brojPrijave;
    }

    /**
     * Sets the value of the brojPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojPrijave(String value) {
        this.brojPrijave = value;
    }

    /**
     * Gets the value of the datumPodnosenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPodnosenja() {
        return datumPodnosenja;
    }

    /**
     * Sets the value of the datumPodnosenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPodnosenja(XMLGregorianCalendar value) {
        this.datumPodnosenja = value;
    }

    public StatusZahteva getStatus() {
		return status;
	}

	public void setStatus(StatusZahteva status) {
		this.status = status;
	}

	public Map<QName, String> getOtherAttributes() {
		return otherAttributes;
	}


	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();
        buffer.append("- Zahtev za autorsko delo: ");
        
        buffer.append("\n\t - Naslov: ");
        buffer.append(naslov);

        buffer.append("\n\t - Broj prijave: ");
        buffer.append(brojPrijave);

        buffer.append("\n\t - Datum podnosenja: ");
        buffer.append(datumPodnosenja);

        buffer.append("\n\t - Zavod: ");
        buffer.append(zavod.toString());

        buffer.append("\n\t - Podnosilac: ");
        buffer.append(podnosilac.toString());

        buffer.append("\n\t - Autorsko delo: ");
        buffer.append(autorskoDelo.toString());

        buffer.append("\n\t - Prilozi: ");
        buffer.append(prilozi.toString());

        return buffer.toString();
	}


}
